### ISSUE TITLE
Question: di.get the only way to instantiate?

### ISSUE THREAD

**Issue by ernsheong** [di-ninja/di-ninja#1]
Is `di.get` the only way to instantiate a class?

Use case:
`document.createElement("some-custom-element")` calls the original constructor directly, bypassing di mechanism. 

Is there a strategy for this use case?

**Comment by takion** [comment]
I'm not sure that I understand what you're trying to achieve, but you can do


```
di.rules({
  'domElement': {
    classDef: function(type){
      return document.createElement(type)
    }
  }
})

const el1 = di.get('domElement', [ di.value("some-custom-element") ])
const el2 = di.get('domElement', [ di.value("another-custom-element") ])

```

and in case of composition root

```
di.rules({
  'domElement': {
    classDef: function(type){
      return document.createElement(type)
    },
    params: [
      di.value("some-custom-element")
    ]
  },
  '#app': {
    shared: true,
    classDef: function(domElement){
      //...
    },
    params: [
      'domElement',
    ]
 }
})

// this can be the only call to di.get and boot the entire tree of your application
di.get('#app')
```

Di-Ninja strategy is to wrap around your components, it will never fork or overwrites natives methods in a hacky way ;)

The main interest of the dependency injection is to wire decoupled components together as a top overlay, but it doesn't means that you have to replace all manual instanciations

**Comment by ernsheong** [comment]
Thanks for the clarification. Will need to play around a bit to really grok all this :)

**Comment by takion** [comment]
class constructor work exactly like function, so you can do

```js
class CustomElement extends HTMLElement {
  constructor(a, b) {
    this.a = a
    this.b = b
  }
}

di.addRules({
  'A': {
    classDef: A,
  },
  'B': {
    classDef: B,
  },
  'CustomElement': {
    classDef: CustomElement,
    params: [ 'A', 'B' ],
  }
})

const customElementInstance = di.get('CustomElement')
```
