### ISSUE TITLE
Doubt about using singleton

### ISSUE THREAD

**Issue by germanst** [di-ninja/di-ninja#4]
Is there any way to add a rule to represent this behavior I need:
Module 1: use singleton of Class A
Module 2: use singleton (different of Module 1's singleton) of Class A.
I did it in following way and it works, but I'm sure is not THE solution:
```
'A': {
  classDef: A,
  shared: true
},
'A2': {
  classDef: A,
  shared: true
},
```
And I use di.get('A') un Module 1 and di.get('A2') un Module 2

**Comment by takion** [comment]
You can do this way, but if you want follow the idea behind Composition-Root approach, you link the components together in one single place

```js
di.addRules({
  'A': {
    classDef: A,
    shared: true
  },
  'A2': {
    classDef: A,
    shared: true
  },
  'Module1': {
    classDef: Module1,
    params: ['A'],
  },
  'Module2': {
    classDef: Module2,
    params: [{
      A2: 'A2',
    }],
    
  },
  'main': {
    classDef: main,
    params: [{
      Module1: 'Module1',
      Module2: 'Module2',
    }],
  },
})

di.get('main')
```


and you have to export factories in Module1, Module2 and main

```js
//Module1.js
export default function(A){
  //and then use A1
}
```

```js
//Module2.js
export default function(A2){
  //and then use A2
}
```

```js
//main.js
export default function({
  // using destructing object in this example fore more readability
  Module1,
  Module2,
}){
  //and then use Module1 and Module2
}
```

**Comment by germanst** [comment]
Great, thank you very much!

**Comment by takion** [comment]
You're welcome,
there was a typo in my example, I just fixed it.

PS: don't forget to star it if you like it ;)
