### ISSUE TITLE
Error `Invalid attempt to spread non-iterable instance` on server side when use `calls` option

### ISSUE THREAD

**Issue by rlalak** [di-ninja/di-ninja#8]
Hi,

I have strange error when I use `calls` option. I use Nuxt + Vue and in browser your container works great but on server side I got error: `Invalid attempt to spread non-iterable instance`. 
After debugging I found  the reason. 
There is condition `if (value instanceof Array) {` in `node_modules/di-ninja/dist/structuredResolveParamsInterface.js:25` that is falsy for array value.
I have no idea why this value is not recognized as `instanceof Array` because when I logging it looks like normal array. If I used `Array.isArray()` the it return `true`.

If I change this line to `if (value instanceof Array || Array.isArray(value)) {` then it start working.
Could you add extra chceck to this line?

**Comment by surikat** [comment]
Hi,

thanks for the feedback,
according to https://stackoverflow.com/questions/22289727/difference-between-using-array-isarray-and-instanceof-array, I opted for more reliable `Array.isArray` method
resolved by https://github.com/di-ninja/di-ninja/commit/7efcb0a218983c78b088e37e9058c1b887b81362
and just published a patched release
`nmp i 1.13.1`
;)

**Comment by rlalak** [comment]
Great, thanks for fast reaction :)
